<a href="https://colab.research.google.com/github/adas754/python_revision-from-day1/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [2]:
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [3]:
import numpy as np
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [4]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [21]:
def get_arr(arr):
  shape=arr.shape
  dim=arr.ndim
  return shape,dim
get_arr(np.array([0,1,2,3,4,5]))

((6,), 1)

In [22]:
def get_ele(arr):
  first=arr[0]
  last=arr[-1]
  return first,last
get_ele(np.array([0,1,2,3,4,5]))

(0, 5)

In [30]:
def seq(start,length,step):
  seq=np.arange(start,start+step*length,step)
  return seq
print(seq(5,10,3))

[ 5  8 11 14 17 20 23 26 29 32]


In [39]:
def create_seq(start,end,step):
  arr=np.arange(start,end,step).round(2)
  return arr
create_seq(5,7,0.5)

array([5. , 5.5, 6. , 6.5])

In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])

6


In [41]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)

[10  2 20  4 30  6 40  8]


In [47]:
def ratio(arr):
  destination=arr[arr>80]
  first_divison=arr[(arr>=60)&(arr<80)]
  destination=len(destination)
  first_divison=len(first_divison)
  ratio=destination/first_divison
  return round(ratio,2)
ratio(np.array([20, 35, 68, 82, 83, 70, 90]))

1.5

In [54]:
def filtered_(arr):
  arr=np.array(arr)
  return arr[arr>40]


print(filtered_([85, 18, 2, 57, 65, 44]))

[85 57 65 44]
